raw_data_table: public.ts_raw_data
raw_data_loader: PostgresqlDataLoader
metrics:
  - metric_name: 'Consumption'
    date_column_name: 'DateTime'
    date_column_format: '%Y-%m-%d %H:%M:%S'
    data_loader: CSVDataLoader
    data_path: './data/electricityConsumptionAndProduction.csv'
    run_period: 'hour'
  - metric_name: 'Production'
    date_column_name: 'DateTime'
    date_column_format: '%Y-%m-%d %H:%M:%S'
    data_loader: CSVDataLoader
    data_preprocessor:
      class_name: ConstantImputeProcessor
      imput_value: 1000
    data_path: './data/electricityConsumptionAndProduction.csv'
    run_period: 'hour'
  - metric_name: 'Nuclear'
    date_column_name: 'DateTime'
    date_column_format: '%Y-%m-%d %H:%M:%S'
    data_loader: CSVDataLoader
    data_preprocessor:
      class_name: ConstantImputeProcessor
      imput_value: 0
    data_path: './data/electricityConsumptionAndProduction.csv'
    run_period: 'hour'
  - metric_name: 'Wind'
    date_column_name: 'DateTime'
    date_column_format: '%Y-%m-%d %H:%M:%S'
    data_loader: CSVDataLoader
    data_path: './data/electricityConsumptionAndProduction.csv'
    run_period: 'hour'
