metrics:
  - metric_name: 'Consumption'
    date_column_name: 'DateTime'
    date_column_format: '%Y-%m-%d %H:%M:%S'
    data_loader: CSVDataLoader
    data_path: './data/electricityConsumptionAndProduction.csv'
    run_period: 'month'
    start_dttm: '2019-01-01 00:00:00'
  - metric_name: 'Production'
    date_column_name: 'DateTime'
    date_column_format: '%Y-%m-%d %H:%M:%S'
    data_loader: CSVDataLoader
    data_preprocessor: ConstantImputeProcessor
    data_path: './data/electricityConsumptionAndProduction.csv'
    run_period: 'month'
    start_dttm: '2019-01-01 00:00:00'
