anomaly_stats_table: public.ts_anomaly_stats_data
metrics:
  - metric_name: 'Consumption'
    raw_data_table: 'public.ts_raw_data'
    is_preprocessing: False
    data_loader: PostgresqlDataLoader
    anomaly_detector: IQRAnomalyDetector
    kwargs:
      IQR_coef: 1.5
      train_period: 30
  - metric_name: 'Production'
    raw_data_table: 'public.ts_raw_data'
    is_preprocessing: False
    data_loader: PostgresqlDataLoader
    anomaly_detector: IQRAnomalyDetector
    kwargs:
      IQR_coef: 1.5
      train_period: 30